### ISSUE TITLE
[Bug]: Not working with bzlmod projects

### ISSUE THREAD

**Issue by condemil** [aspect-build/rules_jest#105] opened 2023-02-18 08:27 UTC
### What happened?

There are at least two issues that I see when I try to use rules_jest with bzlmod project:

1. "entry_point must be a single file or a target that provides a DirectoryPathInfo" error
2. "While resolving toolchains for target //:test: No matching toolchains found for types @rules_nodejs//nodejs:toolchain_type" when there is no toolchain explicitly registered and default toolchain is used, which works fine with js projects and rules_js

### Version

Development (host) and target OS/architectures: Ubuntu 22.04 x86_64

Output of `bazel --version`: bazel 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_jest 0.16.1, aspect_rules_js 1.19.0

Language(s) and/or frameworks involved: JS

### How to reproduce

```shell
1. Clone repo: https://gist.github.com/condemil/25445ca034f426c4a4b4853c0bf951e5
2. Run `bazel test //:test`
3. Observe "entry_point must be a single file or a target that provides a DirectoryPathInfo" error
4. Remove rules_nodejs dependency and toolchain registration from `MODULE.bazel`
5. Run `bazel test //:test`
6. Observe "While resolving toolchains for target //:test: No matching toolchains found for types @rules_nodejs//nodejs:toolchain_type" error
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment] 2023-02-18 16:21
I believe the toolchain issue you're hitting here when bzlmod is enabled is due to this Bazel 6 bug: https://github.com/bazelbuild/bazel/issues/17289

The principled fix is to add bzlmod support to rules_jest: https://github.com/aspect-build/rules_jest/issues/79

We're tracking that work for all of the downstream rules_js repos here: https://github.com/aspect-build/rules_js/issues/63

**Comment by amardeep** [comment] 2023-03-03 07:20
I am also facing the same issue, and adding a platforms dep doesn't fix it

**Comment by gregmagolan** [comment] 2023-03-04 03:38
> I am also facing the same issue, and adding a platforms dep doesn't fix it

We should probably just get rules_jest onto bzlmod sooner rather than later since it is widely used.

**Comment by gregmagolan** [comment] 2023-04-10 05:50
Closing this as a duplicate of https://github.com/aspect-build/rules_jest/issues/79. bzlmod support should land soon with https://github.com/aspect-build/rules_jest/pull/113.

**Closed by gregmagolan** 2023-04-10 05:50 UTC
Labels: bug, blocked
